### ISSUE TITLE
Need to add tests

### ISSUE THREAD

**Issue by katzfuss** [katzfuss-group/GPvecchia#13]
We should probably have some tests that need to be run before pushing any commits, to make sure the code changes are not breaking any important functionality. Not sure what the optimal procedure for this is.

**Comment by marcinjurek** [comment]
It seems like [one of the popular ways](https://blog.github.com/2017-11-07-github-welcomes-all-ci-tools/) is to use Travis CI. [Some people object to running unit tests before every commit](https://softwareengineering.stackexchange.com/questions/260778/is-it-a-good-practice-to-run-unit-tests-in-version-control-hooks) but I'm not sure if the two main concerns (commit speed and security) they mention are that relevant in our case.

For starters, however, maybe it would be good to estabilish some test cases. I could then write a short R script for each of them them, put in a separate directory and everyone can run them whenever pushing.

Working on pyMRA I used 1d exp cov function with knots on the split points, which we've known to be exact. 

Are there any other similar cases for general vecchia where we would know the results are exact? Or at least we know for sure what they should be?

**Comment by katzfuss** [comment]
Thanks for researching this. Yes, some test cases that can be run manually should suffice for now.

Vecchia is also exact for exponential covariance in 1D:

```
n=10
locs=matrix(1:n,ncol=1)
z=rep(1,n)

## vecchia
vecchia.approx=vecchia_specify(locs,1)
vecchia_likelihood(z,vecchia.approx,c(1,1,.5),1)

## compare to exact likelihood
library(mvtnorm)
cov.mat=exp(-fields::rdist(locs))+diag(n)
dmvnorm(z,mean=rep(0,n),sigma=cov.mat,log=TRUE)
```

In general, it is also exact if m=n-1:

```
n=10
locs <- cbind(1:n,sin(1:n))
z=rep(1,n)

## vecchia
vecchia.approx=vecchia_specify(locs,n-1)
vecchia_likelihood(z,vecchia.approx,c(1,1,.5),1)

## compare to exact likelihood
library(mvtnorm)
cov.mat=exp(-fields::rdist(locs))+diag(n)
dmvnorm(z,mean=rep(0,n),sigma=cov.mat,log=TRUE)
```

But just two special cases, so some more test cases (e.g., for VL -- @dzilber) would be good to have. One issue is that the maxmin ordering is currently random, so the result might be slightly different every time code is run.

**Comment by marcinjurek** [comment]
We can use some version of the script written for method timing for the SGV paper.

**Comment by marcinjurek** [comment]
@dzilber I feel like you and I contribute the most code atm. I'm thinking of using some of these R packages for unit testing so that our process is more formalized. What are your thoughts on this? I remember some time ago you said you typically run the vignette. Since then I tried to adopt the same custom for my MRA code. The problem with that, however, is that oftentimes there are things that to a trained eye just "look right". This is more cumbersome and hard to monitor as our package grows. Anyway, I'm not entirely sure what the best way to do this is, but I feel pretty strongly about the need to have some established testing process. I have some ideas but I was wondering what you think as well.

**Comment by dzilber** [comment]
@marcinjurek Agreed, I use the vignettes as a substitute for unit testing, but unit tests are the right tool to use. I believe there are ways to link the unit tests to git so that every commit triggers a run of the unit tests, and if any test fails it sends a message to the person committing.  

The tests suggested by @katzfuss make sense, and we can also add for the case m=0.   Later I will try to make a test in the naive way, ie: set a random seed, generate a small data set, perform the methods, and use the (rounded) output we currently get as the correct or true value for the given seed and scenario.

**Comment by marcinjurek** [comment]
Okay, so here is the road map based on Hadley Wickam's book http://r-pkgs.had.co.nz/tests.html and Karl Broman's post https://kbroman.org/pkg_primer/pages/tests.html and my own thoughts on this

- [ ] come up with a set of tests that use the `assert` statement.
This will give us the material to work with - actual tests. At the same time it is very easy to develop and we don't worry about packages or antyhing like that. We will just have a bunch of files we can manually run
- [ ] put these tests into the `tests` directory
- [ ] use Wickam's tutorial and the `testthat` package to convert the `assert`s into `expect_equal`s. These tests will be run whenever one runs `R CMD check` on the package
- [ ] hook these tests up to Travis CI per instructions in the Broman's article.

**Comment by marcinjurek** [comment]
make sure that the standard vignette does not produce any errors
- vecchia_specify, vecchia_likelihood, vecchia_prediction

**Comment by marcinjurek** [comment]
this will be done whenever R CMD check is run; the vignettes and the tests are run then
