### ISSUE TITLE
MRA improvements

### ISSUE THREAD

**Issue by katzfuss** [katzfuss-group/GPvecchia#26]
MRA-type Vecchia approximations can be computed using vecchia_specify with option conditioning='mra'. In that case, we should set ordering='maxmin' automatically.

In addition, we need to have an optional argument mra.settings, which is a list with potential entries M, r, and J. M must be a scalar, and r and J can be scalars or vectors of length M and M-1, respectively. If M>1 but r or J are scalars, we assume that r and J are supposed to be the same for each resolution.
If M, r, and J are all specified, they should override m, but we should print a warning that says so. If at least one of M, r, and J are not specified, we should determine reasonable default values based on m (and n), ensuring that no conditioning set is larger than m.

Please ensure that the code can handle the following special cases:
- m=20, M=0: Independent blocks: The locations would be split into groups of maximum size 20+1=21, and each group is then assumed to be independent.
- m=20, M=1: Block-full-scale approximation: Pick the first r_0 = 20/2 = 10 locations in maxmin ordering as knots at resolution 0, then split the remaining locations into groups of maximum size 10+1=11.
- r=c(20,0): Modified predictive process: Pick the first 20 locations in maxmin ordering as knots at resolution 0, then treat all remaining locations as conditionally independent.

Also, I believe for package building etc to work correctly, all R code must be in the "R" folder. So please move your MRA R code from "MRA" to "R", but please also combine the functions into a small number of files (maybe 1-4). Tests can be moved to the "tests" folder.

**Comment by marcinjurek** [comment]
one thing that's somewhat complicated to implement right now is a clustering/domain partitioning algorithm that would ensure there is at most _k_ points in a given cluster. This problem comes up for example in bullet points 1 and 2.

I followed some of the links we talked about at our meeting but haven't foudn any quick fix. What I'm going to do right now is as follows:

- calculate `K = ceil(n/k)` and use this as a number of clusters. 
- run K-means with `K` 

On average each cluster will have a prescribed number of points. I'm just writing it here for the record, so that we don't forget about it.

**Comment by marcinjurek** [comment]
I just pushed a solution in commit 92952cd  (a separate `ticket26` branch). In order to see how it works, one needs to run `tests/test-ticket26.r `. I came up with 6 test cases which, I thought, cover all of the important parameter settings. Could you please have a look at it? I only tested it in 2d. For 1d it works without error but something is wrong with the plots. I'm going to investigate it, but I just wanted to push it quickly to get your feedback.

**Comment by marcinjurek** [comment]
Added two important updates to the `ticket26` branch. The plotting issue is fixed now. Also removed a small bug that upset an MRA with M>1. (I added another test case for that now).

**Comment by marcinjurek** [comment]
I'm closing this ticket now. I opened a new one to track issues with the existing solution to the requests described here.
