### ISSUE TITLE
add checks to prevent C++ crashes

### ISSUE THREAD

**Issue by marcinjurek** [katzfuss-group/GPvecchia#52]
Apparently sometimes the RStudio session crashes after calling an Rcpp function. @dzilber, if you see it happen, please paste an example here.

**Comment by dzilber** [comment]
Crash 1:  VL gets data that does not match the distribution domain.  For example, specifying Gamma distributed data but passing in negative values.  The C++ code crashes somewhere, probably due to NA or -infty.  A check for data integrity handles the problem.

Crash 2:  I can reproduce it, but I don't know what is causing it.

```

source("server/importer.R")

global_m = 5 # 20 40
n = 2500
a = 0.88
covparms = c(0.9, 1,   1.5)


# Generate a large data set
locs = cbind(runif(n)*10, runif(n)*10)
locs = as.matrix(locs)
K= covparms[1]*Matern(rdist(locs), range = covparms[2], smoothness = covparms[3])
y = t(chol(K))%*%rnorm(n)
z = rgamma(y, shape = a, rate = a*exp(-y))

# Take a subsample of the data set
n_sample = 250
sub_idx = sample(length(z), n_sample, replace = FALSE)
sub_locs = locs[sub_idx,]; z_sub = z[sub_idx]

X = sub_locs; X[,1]= 1;beta = matrix(c(-1.515079549, 0.000765648))
XB = X%*% beta

vecchia.approx = vecchia_specify(sub_locs, m=global_m, cond.yz = "zy")
post_zy = calculate_posterior_VL(z_sub, vecchia.approx,
                                 "gamma" , covparms,
                                 likparms = list("alpha"=a), prior_mean = XB)

## Perform predictions on another subsample, which may overlap with the original
zoom_idx = intersect(which(locs[,1] >5 & locs[,1]<10),  which(locs[,2] <10 & locs[,2] > 5))
locs_zoom = locs[zoom_idx,]; z_zoom =z[zoom_idx]
trend_zoom = locs_zoom; trend_zoom[,1]=1
XB_zoom = trend_zoom%*%beta

z_VLpseudo = post_zy$t - XB
nuggets_VLpseudo = post_zy$D
vecchia.approx.zoom = vecchia_specify(sub_locs, m=global_m, locs.pred=locs_zoom)
preds_zoom=vecchia_prediction(z_VLpseudo, vecchia.approx.zoom, covparms, nuggets_VLpseudo)
```

**Comment by dzilber** [comment]
I realized the second issue I describe above is due the prediction locations containing observed locations.  I added a check that stops the code if it finds a non-empty intersection between locs and locs.pred.  This can be modified to automatically remove the redundant locations, but that is left for another ticket.

**Comment by dzilber** [comment]
The second issue with a check for repeated prediction locations is trickier than I thought and my current fix doesn't work for more complicated samples.  If you are using it, set the if-statement to something that is always false.  Should have a fix soon.

**Comment by katzfuss** [comment]
@dzilber Maybe we could simply check for duplicates in the entire location matrix (observation and prediction combined) using anyDuplicated()? Try
```
locs.all=matrix(rpois(1e5*2,1e6),ncol=2)
system.time(anyDuplicated(locs.all)>0)
```

If we add such a check to vecchia_specify(), maybe the added computation time would not be too bad?

**Comment by dzilber** [comment]
The issues I mentioned should be resolved now and have been checked for the test cases provided.  The method to check for duplicates provided by @katzfuss is fast and clean and has been implemented.  It checks 10 million 2D integer locations in about 2 seconds.  100 million was much slower, but that may have to do with my limited RAM, and I think it will not be the bottleneck. 

I saw that large non-Gaussian values can cause C++ crashes when not corrected by a mean term, but this is more a matter of machine precision and I will ignore it.  Otherwise I have not encountered any other edge cases that cause crashes and will close the ticket.
