### ISSUE TITLE
VL likelihood and predictions do not handle mean terms correctly

### ISSUE THREAD

**Issue by dzilber** [katzfuss-group/GPvecchia#59]
The prior mean term was not being used correctly in these methods:

```
data.distr = 'gaussian' #options: "gaussian","logistic", "poisson", "gamma"
spatial.dim = 2 # number of spatial dimensions
n = 40^2 # number of observed locs

default_lh_params = list("alpha"=2, "sigma"=sqrt(.1))
locs <- cbind(runif(n),runif(n))

# covariance parameters
sig2=1; range=.2; smooth = 1.5
covparms=c(sig2, range, smooth)
covfun <- function(locs) sig2*Matern(fields::rdist(locs),range=range,smoothness=smooth)

# simulate latent process
Om0 <- covfun(locs)
# add prior mean
y=as.numeric(t(chol(Om0))%*%rnorm(n))+4 

# simulate data
nuggets=rep(default_lh_params$sigma^2,n)
z = rnorm(n,y,sqrt(nuggets))

m=5
vecchia.approx=vecchia_specify(locs,m,cond.yz='zy') #RF ordering

vll1 = vecchia_laplace_likelihood(z,vecchia.approx,likelihood_model=data.distr,covparms, likparms = default_lh_params, prior_mean =4)

vll2 = vecchia_laplace_likelihood(z-4,vecchia.approx,likelihood_model=data.distr,covparms, likparms = default_lh_params, prior_mean = 0)

# two likelihoods should be equal
vll1==vll2
```

**Comment by katzfuss** [comment]
Please make sure to also test with spatially varying mean.

As a reminder, here is what I had sent regarding this issue:

Should prior_mean be subtracted in line 321 of https://github.com/katzfuss-group/GPvecchia/blob/master/R/vecchia_laplace_NR.R ? 
And vecchia_laplace_prediction() should have access to prior_mean and prior_mean_pred (at unobserved prediction locations), so that we can subtract prior_mean before calling vecchia_prediction() and add back prior_mean and prior_mean_pred to the prediction means.
Or to avoid having to always subtract prior_mean from the pseudo-data, would it be easier to simply not add back the mean in line 122?

I'm fairly certain that lines 362-363, which currently are
data_preds$data.pred <- vl_posterior$data_link(preds$mu.pred+vl_posterior$prior_mean) 
data_preds$data.obs <- vl_posterior$data_link(preds$mu.obs)  
should actually be
data_preds$data.pred <- vl_posterior$data_link(preds$mu.pred+prior_mean_pred) 
data_preds$data.obs <- vl_posterior$data_link(preds$mu.obs+vl_posterior$prior_mean)  
where prior_mean_pred is the latent mean at the unobserved prediction locations.

**Comment by dzilber** [comment]
In addition to the fixes mentioned by @katzfuss , there was the additional issue that the `preds` object  was not being corrected for the mean.  Fixing this made the corrections to the `data_preds` terms unnecessary.  Based on my testing, both likelihood and predictions are now correctly handling mean terms. 

Regarding the pseudo_data + prior_mean term returned by calculate_posterior_VL method, I think that is the expected output and it matches the posterior mean, so I will leave it as is for now.
